homeassistant:
  # Name of the location where Home Assistant is running
  name: Pi4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

#logger:
#  default: error
#  logs:
#    rflink: debug
#    homeassistant.components.rflink: debug


#http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret api_password
  # use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

config:

#frontend:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

sensor:
  - platform: dht
    sensor: AM2302
    pin: 4
    monitored_conditions:
      - temperature
      - humidity

automation:
######### SENSOR PROPAGATION SLAVE->MASTER (MQTT) #########
  - id: technofire_json
    alias: Technofire JSON
    trigger:
        platform: mqtt
        topic: "home/technofire/pi4/jsonset"
    action:
        - service: shell_command.technofire
          data_template:
             scene: '{{ trigger.payload_json.scene }}'
             brightness: '{{ trigger.payload_json.brightness }}'
        - service: mqtt.publish
          data_template:
              topic: "home/technofire/pi4/state"
              payload: '{% if trigger.payload_json.scene == "off" %}OFF{% else %}ON{% endif %}'
  - id: technofire
    alias: Technofire
    trigger:
        platform: mqtt
        topic: "home/technofire/pi4/set/#"
    action:
        - service: shell_command.technofire
          data_template:
             scene: '{% if trigger.payload == "OFF" %}off{% else %}{{ trigger.topic.split("/")[-2] }}{% endif %}'
             brightness: '{{ trigger.topic.split("/")[-1] }}'
        - service: mqtt.publish
          data_template:
              topic: "home/technofire/pi4/state"
              payload: '{% if trigger.topic.split("/")[-2] == "off" or trigger.payload == "OFF" %}OFF{% else %}ON{% endif %}'
  - id: s2m_dht_sensor_temperature
    alias: s2m_dht_sensor_temperature
    trigger:
        - platform: state
          entity_id: sensor.dht_sensor_temperature
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll
    action:
        service: mqtt.publish
        data:
            topic: "home/sensor/temperature_attic"
            payload_template: "{{ states('sensor.dht_sensor_temperature') }}"
  - id: s2m_dht_sensor_humidity
    alias: s2m_dht_sensor_humidity
    trigger:
        - platform: state
          entity_id: sensor.dht_sensor_humidity
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll
    action:
        service: mqtt.publish
        data:
            topic: "home/sensor/humidity_attic"
            payload_template: "{{ states('sensor.dht_sensor_humidity') }}"

shell_command:
    technofire: 'sudo /home/homeautomation/homeassistant/scripts/technofire/technofire.sh {{ scene.replace(" ","_") | lower }} {{ brightness }} 60'

#MQTT
mqtt:
    broker: 192.168.0.1
    port: 8883
    client_id: pi4
    certificate: /etc/ssl/certs/ca-certificates.crt
    tls_insecure: true #allow non-matching hostnames
    keepalive: 60
    username: homeassistant
    password: !secret api_password

#mqtt_eventstream:
#  publish_topic: slaves/pi2
#  subscribe_topic: master
