homeassistant:
  # Name of the location where Home Assistant is running
  name: Pi1
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam


#http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr


binary_sensor:
    - platform: rpi_gpio
      ports:
        25: frontdoor
      invert_logic: false
      bouncetime: 60
    - platform: rpi_gpio
      ports:
        18: doorbell
      invert_logic: true
      bouncetime: 60


switch:
    platform: command_line
    switches:
        tv_spots:
            friendly_name: TV Spots
            command_on: "/home/homeautomation/43392/433send beneden 16 1"
            command_off: "/home/homeautomation/43392/433send beneden 16 0"

#MQTT
mqtt:
    broker: 192.168.0.1
    port: 1883
    client_id: pi1
    keepalive: 60
    username: homeassistant
    password: !secret api_password

mqtt_eventstream:
  publish_topic: slaves/pi1
  subscribe_topic: master
