homeassistant:
  # Name of the location where Home Assistant is running
  name: Pi1
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

#frontend:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr


binary_sensor:
    - id: slave_frontdoor
      platform: rpi_gpio
      ports:
        25: slave_frontdoor
      pull_mode: DOWN
      invert_logic: true
      bouncetime: 60
      device_class: opening
    - id: slave_doorbell
      platform: rpi_gpio
      ports:
        18: slave_doorbell
      pull_mode: DOWN
      invert_logic: false
      bouncetime: 60


switch:
    platform: command_line
    switches:
        tv_spots:
            command_on: /home/homeautomation/43392/433send -g beneden -d 16 -s 1
            command_off: /home/homeautomation/43392/433send -g beneden -d 16 -s 0
        front_room:
            command_on: /home/homeautomation/43392/lights/kaku M 10 on
            command_off: /home/homeautomation/43392/lights/kaku M 10 off
        hall:
            command_on: /home/homeautomation/43392/433send -g boven -d 2 -s 1
            command_off: /home/homeautomation/43392/433send -g boven -d 2 -s 0


######### SENSOR PROPAGATION SLAVE->MASTER (MQTT) #########
automation s2m_frontdoor:
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.frontdoor
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/frontdoor"
            payload_template: "{{ states('binary_sensor.frontdoor') | upper }}"

automation s2m_doorbell:
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.doorbell
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/doorbell"
            payload_template: "{{ states('binary_sensor.doorbell') | upper }}"

######### SWITCH PROPAGATION SLAVE->MASTER and MASTER->SLAVE (MQTT) #########
automation s2m_tv_spots:
    hide_entity: true
    trigger:
        - platform: state
          entity_id: switch.tv_spots
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/switch/tv_spots"
            payload_template: "{{ states('switch.tv_spots') | upper }}"

automation m2s_tv_spots:
     hide_entity: true
     trigger:
        platform: mqtt
        topic: "home/switch/tv_spots"
     action:
        service_template: switch.turn_{{ trigger.payload | string | lower }}
        entity_id: switch.tv_spots

automation s2m_front_room:
    hide_entity: true
    trigger:
        - platform: state
          entity_id: switch.front_room
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/switch/front_room"
            payload_template: "{{ states('switch.front_room') | upper }}"

automation m2s_front_room:
     hide_entity: true
     trigger:
        platform: mqtt
        topic: "home/switch/front_room"
     action:
        service_template: switch.turn_{{ trigger.payload | string | lower }}
        entity_id: switch.front_room

automation s2m_hall:
    hide_entity: true
    trigger:
        - platform: state
          entity_id: switch.hall
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/switch/hall"
            payload_template: "{{ states('switch.hall') | upper }}"

automation m2s_hall:
     hide_entity: true
     trigger:
        platform: mqtt
        topic: "home/switch/hall"
     action:
        service_template: switch.turn_{{ trigger.payload | string | lower }}
        entity_id: switch.hall

automation startup:
  hide_entity: true
  trigger:
      platform: homeassistant
      event: start
  action:
      service: shell_command.start_pycec

shell_command:
    start_pycec: python -m pycec
    tvdecoder_volup: irsend SEND_ONCE VIP1853 UP &
    tvdecoder_voldown: irsend SEND_ONCE VIP1853 DOWN &
    tvdecoder_chanup: irsend SEND_ONCE VIP1853 CHANNEL_UP &
    tvdecoder_chandown: irsend SEND_ONCE VIP1853 CHANNEL_DOWN &
    tvdecoder_ok: irsend SEND_ONCE VIP1853 OK &
    tvdecoder_back: irsend SEND_ONCE VIP1853 BACK &
    tvdecoder_down: irsend SEND_ONCE VIP1853 DOWN &
    tvdecoder_up: irsend SEND_ONCE VIP1853 UP &
    tvdecoder_right: irsend SEND_ONCE VIP1853 RIGHT &
    tvdecoder_left: irsend SEND_ONCE VIP1853 LEFT &
    tvdecoder_mute: irsend SEND_ONCE VIP1853 MUTE &
    tvdecoder_pause: irsend SEND_ONCE VIP1853 PAUSE &
    tvdecoder_1: irsend SEND_ONCE VIP1853 KEY_1 &
    tvdecoder_2: irsend SEND_ONCE VIP1853 KEY_2 &
    tvdecoder_3: irsend SEND_ONCE VIP1853 KEY_3 &
    tvdecoder_4: irsend SEND_ONCE VIP1853 KEY_4 &
    tvdecoder_5: irsend SEND_ONCE VIP1853 KEY_5 &
    tvdecoder_6: irsend SEND_ONCE VIP1853 KEY_6 &
    tvdecoder_7: irsend SEND_ONCE VIP1853 KEY_7 &
    tvdecoder_8: irsend SEND_ONCE VIP1853 KEY_8 &
    tvdecoder_9: irsend SEND_ONCE VIP1853 KEY_9 &
    tvdecoder_0: irsend SEND_ONCE VIP1853 KEY_0 &
    avr_mute: irsend SEND_ONCE avr KEY_MUTE &
    avr_volup: irsend SEND_ONCE avr KEY_VOLUMEUP &
    avr_voldown: irsend SEND_ONCE avr KEY_VOLUMEDOWN &
    avr_voldown: irsend SEND_ONCE avr KEY_VOLUMEDOWN &




#MQTT
mqtt:
    broker: 192.168.0.1
    port: 1883
    client_id: pi1
    keepalive: 60
    username: homeassistant
    password: !secret api_password

#mqtt_eventstream:
#  publish_topic: slaves/pi2
#  subscribe_topic: master
