homeassistant:
  # Name of the location where Home Assistant is running
  name: Pi1
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

#frontend:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr


binary_sensor:
    - id: frontdoor
      platform: rpi_gpio
      ports:
        25: frontdoor
      pull_mode: DOWN
      invert_logic: true
      bouncetime: 60
      device_class: opening
    - id: doorbell
      platform: rpi_gpio
      ports:
        18: doorbell
      pull_mode: DOWN
      invert_logic: false
      bouncetime: 60

switch:
    platform: command_line
    switches:
        kodi:
            command_on: "kodi-standalone &"
            command_off: "killall kodi-standalone kodi kodi_v7.bin"
            command_state: "ps aux | grep kodi | grep -v grep"
        xorg:
            command_on: "startx &"
            command_off: "killall Xorg"
            command_state: "ps aux | grep Xorg | grep -v grep"

######### SENSOR PROPAGATION SLAVE->MASTER (MQTT) #########
automation:
  - id: s2m_frontdoor
    alias: s2m_frontdoor
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.frontdoor
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/frontdoor"
            payload_template: "{{ states('binary_sensor.frontdoor') | upper }}"
  - id: s2m_doorbell
    alias: s2m_doorbell
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.doorbell
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/doorbell"
            payload_template: "{{ states('binary_sensor.doorbell') | upper }}"
  - id: s2m_kodi
    alias: s2m_kodi
    trigger:
        - platform: state
          entity_id: switch.kodi
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/kodi/get/pi1"
            payload_template: "{{ states('switch.kodi') | upper }}"
  - id: s2m_xorg
    alias: s2m_xorg
    trigger:
        - platform: state
          entity_id: switch.xorg
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/xorg/get/pi1"
            payload_template: "{{ states('switch.xorg') | upper }}"
  - id: m2s_kodi
    alias: m2s_kodi
    trigger:
        platform: mqtt
        topic: "home/kodi/set/pi1"
    action:
        service_template: switch.turn_{{trigger.payload|lower}}
        entity_id: switch.kodi
  - id: m2s_xorg
    alias: m2s_xorg
    trigger:
        platform: mqtt
        topic: "home/xorg/set/pi1"
    action:
        service_template: switch.turn_{{trigger.payload|lower}}
        entity_id: switch.kodi




######### SWITCH PROPAGATION SLAVE->MASTER and MASTER->SLAVE (MQTT) #########
  - id: startup
    alias: Startup
    hide_entity: true
    trigger:
       platform: homeassistant
       event: start
    action:
       service: shell_command.start_pycec

  - id: ir_send
    alias: IR Send
    trigger:
        platform: mqtt
        topic: "home/ir_send/pi1"
    action:
        service: shell_command.ir_send
        data_template:
            device: '{{ trigger.payload_json.device }}'
            key: '{{ trigger.payload_json.key }}'
  - id: 433send
    alias: 433send
    trigger:
        platform: mqtt
        topic: "home/433send/set/pi1/#"
    action:
        - service: shell_command.433send
          data_template:
             protocol: '{{ trigger.topic.split("/")[-3] }}'
             group: '{{ trigger.topic.split("/")[-2] }}'
             unit: '{{ trigger.topic.split("/")[-1] }}'
             state: '{{ trigger.payload|lower }}'
        - service: mqtt.publish
          data_template:
              topic_template: "home/433send/get/{{ trigger.topic.split('/')[-3] }}/{{ trigger.topic.split('/')[-2] }}/{{ trigger.topic.split('/')[-1] }}"
              payload_template: '{{ trigger.payload }}'

shell_command:
    start_pycec: python -m pycec
    ir_send: /home/homeautomation/homeassistant/scripts/media/irsend.sh "{{ device }}" "{{ key }}"
    433send: /home/homeautomation/homeassistant/scripts/switch/433send.sh 8 "{{ protocol }}" "{{ group }}" "{{ unit }}" "{{ state }}"




#MQTT
mqtt:
    broker: 192.168.0.1
    port: 1883
    client_id: pi1
    keepalive: 60
    username: homeassistant
    password: !secret api_password

#mqtt_eventstream:
#  publish_topic: slaves/pi1
#  subscribe_topic: master
