homeassistant:
  # Name of the location where Home Assistant is running
  name: Pi2
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam




http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

frontend:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr


binary_sensor:
    - platform: rpi_gpio
      ports:
        25: backdoor
        17: bedroomwindow_right
        22: bedroomwindow_left
      pull_mode: DOWN
      invert_logic: true
      bouncetime: 60
      device_class: opening


switch:
    platform: command_line
    switches:
        midspots:
            command_on: /home/homeautomation/43392/433send -g beneden -d 2 -s 1
            command_off: /home/homeautomation/43392/433send -g beneden -d 2 -s 0
        back_room:
            command_on: /home/homeautomation/43392/433send -g beneden -d 1 -s 1
            command_off: /home/homeautomation/43392/433send -g beneden -d 1 -s 0
        back_corner:
            command_on: /home/homeautomation/43392/433send -g beneden -d 4 -s 1
            command_off: /home/homeautomation/43392/433send -g beneden -d 4 -s 0
        office:
            command_on: /home/homeautomation/43392/433send -g boven -d 1 -s 1
            command_off: /home/homeautomation/43392/433send -g boven -d 1 -s 0
        bedroom:
            command_on: /home/homeautomation/43392/433send -g boven -d 4 -s 1
            command_off: /home/homeautomation/43392/433send -g boven -d 4 -s 0
        garden:
            command_on: /home/homeautomation/43392/433send -g buiten -d 1 -s 1
            command_off: /home/homeautomation/43392/433send -g buiten -d 1 -s 0
        balcony:
            command_on: /home/homeautomation/43392/433send -g buiten -d 2 -s 1
            command_off: /home/homeautomation/43392/433send -g buiten -d 2 -s 0
        roof:
            command_on: /home/homeautomation/43392/433send -g buiten -d 4 -s 1
            command_off: /home/homeautomation/43392/433send -g buiten -d 4 -s 0

automation:
######### SENSOR PROPAGATION SLAVE->MASTER (MQTT) #########
  - id: s2m_backdoor
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.backdoor
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll #an explicit re-poll of states, issued by master when it starts
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/backdoor"
            payload_template: "{{ states('binary_sensor.backdoor') | upper }}"

  - id: s2m_bedroomwindow_right
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.bedroomwindow_right
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/bedroomwindow_right"
            payload_template: "{{ states('binary_sensor.bedroomwindow_right') | upper }}"
  - id: s2m_bedroomwindow_left
    hide_entity: true
    trigger:
        - platform: state
          entity_id: binary_sensor.bedroomwindow_left
        - platform: homeassistant
          event: start
        - platform: mqtt
          topic: home/poll
    action:
        service: mqtt.publish
        data:
            topic: "home/binary_sensor/bedroomwindow_left"
            payload_template: "{{ states('binary_sensor.bedroomwindow_left') | upper }}"
  - id: elro_send
    alias: ELRO Send (433.92Mhz)
    trigger:
        platform: mqtt
        topic: "home/elro/set/pi2/#"
    action:
        - service: shell_command.elro_send
          data_template:
             group: '{{ trigger.topic.split("/")[-2] }}'
             unit: '{{ trigger.topic.split("/")[-1] }}'
             state: '{% if trigger.payload|upper == "ON" %}1{% else %}0{% endif %}'
        - service: mqtt.publish
          data_template:
              topic_template: "home/elro/get/{{ trigger.topic.split('/')[-2] }}/{{ trigger.topic.split('/')[-1] }}"
              payload_template: '{{ trigger.payload }}'
  - id: kaku_send
    alias: Klik-aan-Klik-Uit Send (433.92Mhz)
    trigger:
        platform: mqtt
        topic: "home/kaku/set/pi2/#"
    action:
        - service: shell_command.kaku_send
          data_template:
             group: '{{ trigger.topic.split("/")[-2] }}'
             unit: '{{ trigger.topic.split("/")[-1] }}'
             state: '{{ trigger.payload|lower }}'
        - service: mqtt.publish
          data_template:
              topic_template: "home/kaku/get/{{ trigger.topic.split('/')[-2] }}/{{ trigger.topic.split('/')[-1] }}"
              payload_template: '{{ trigger.payload }}'

shell_command:
    start_pycec: python -m pycec
    ir_send: /home/homeautomation/homeassistant/scripts/media/irsend.sh "{{ device }}" "{{ key }}"
    elro_send: /home/homeautomation/homeassistant/scripts/switch/elro.sh "{{ group }}" "{{ unit }}" "{{ state }}"
    kaku_send: /home/homeautomation/homeassistant/scripts/switch/kaku.sh "{{ group }}" "{{ unit }}" "{{ state }}" #Klik-aan-klik-uit

#MQTT
mqtt:
    broker: 192.168.0.1
    port: 1883
    client_id: pi2
    keepalive: 60
    username: homeassistant
    password: !secret api_password

#mqtt_eventstream:
#  publish_topic: slaves/pi2
#  subscribe_topic: master
