- alias: Startup notification
  hide_entity: True
  trigger:
      platform: homeassistant
      event: start
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Home automation started
- alias: Frontdoor snapshots
  hide_entity: True
  trigger:
    platform: time
    seconds: '/9' #every ten seconds
  action:
    - service: shell_command.snapshot_frontdoor
- alias: Hall upstairs snapshots
  hide_entity: True
  trigger:
    platform: time
    seconds: '/11' #every eleven seconds
  action:
    - service: shell_command.snapshot_hallupstairs
- alias: Living room camera snapshots
  hide_entity: True
  trigger:
    platform: time
    seconds: '/3' #every five seconds
  action:
    - service: shell_command.snapshot_livingroom
- alias: Street camera snapshots
  hide_entity: True
  trigger:
    platform: time
    seconds: '/3' #every three seconds
  action:
    - service: shell_command.snapshot_street
- alias: Garden camera snapshots
  hide_entity: True
  trigger:
    platform: time
    seconds: '/5' #every five seconds
  action:
    - service: shell_command.snapshot_garden
- alias: Archive snapshots
  hide_entity: True
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: shell_command.archive_snapshots



