- alias: Startup - Starting system
  hide_entity: True
  trigger:
      platform: homeassistant
      event: start
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Home automation started
