#------------ Startup notification ------------------------
- alias: Startup
  hide_entity: True
  trigger:
      platform: homeassistant
      event: start
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Home automation started
      - service: shell_command.snapshot_clear_locks #clear all snapshot locks on startup
      - service: script.turn_on  #trigger RPi slaves to send their known statusses again
        data:
            entity_id: script.trigger_slave_poll
      - service: script.turn_on
        data:
            entity_id: script.reset_lights
      - service: notify.xmpp_proycon
        data:
            message: "Home automation started"


#------------ Snapshots ------------------------
- alias: Frontdoor snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/9' #every ten seconds
  action:
    - service: shell_command.snapshot_frontdoor
- alias: Hall upstairs snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/11' #every eleven seconds
  action:
    - service: shell_command.snapshot_hallupstairs
- alias: Living room snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every five seconds
  action:
    - service: shell_command.snapshot_livingroom
- alias: Street camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every three seconds
  action:
    - service: shell_command.snapshot_street
- alias: Garden snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/5' #every five seconds
  action:
    - service: shell_command.snapshot_garden
- alias: Daily snapshot archiving
  hide_entity: False
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: shell_command.archive_snapshots
- alias: Door notification at night
  trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
      - platform: state
        entity_id: binary_sensor.back_door
        to: "on"
  condition:
      - condition: time
        after: '23:00:00'
        before: '05:00:00'
      - condition: state
        entity_id: binary_sensor.anybodyhome
        state: "on"
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Door open
- id: lights_on_in_the_evening
  alias: Lights on in the evening
  trigger:
      platform: sun
      event: sunset
      offset: '-00:45:00'
  action:
      service: switch.turn_on
      entity_id: group.living_lights
- id: garden_lights_on_in_the_evening
  alias: Garden lights on in the evening
  trigger:
      platform: sun
      event: sunset
      offset: '01:00:00'
  action:
      service: switch.turn_on
      entity_id: group.garden_lights
- id: lights_off_at_night
  alias: Lights off at night
  trigger:
      platform: time
      at: '01:00:00'
  action:
      service: switch.turn_off
      entity_id: group.all_lights
- id: doorbell
  alias: Doorbell
  trigger:
      platform: state
      entity_id: binary_sensor.doorbell
      from: "off"
      to: "on"
  action:
      - service: script.turn_on
        entity_id: script.doorbell_sound
      - service: notify.xmpp_proycon
        data:
            message: "There is somebody at the door"
      - service: notify.xmpp_hans
        data:
            message: "De deurbel gaat"
- id: ipcam_topreset
  alias: Camera to preset
  trigger:
      platform: state
      entity_id: input_select.ipcam_direction
  action:
      service: script.turn_on
      entity_id: script.ipcam_topreset
- id: alarm_trigger
  alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_left
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_right
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: script.turn_on
      entity_id: script.alarm
    - service: switch.turn_on
      entity_id: group.all_lights
    - service: notify.xmpp_proycon
      data:
          message: "INTRUDER ALERT!! ALARM TRIGGERED!!! CHECK IMMEDIATELY!!!"
    - service: notify.xmpp_hans
      data:
          message: "INTRUDER ALERT!! ALARM TRIGGERED!!! CHECK IMMEDIATELY!!!"
- id: arm_when_away
  alias: 'Arm when away'
  trigger:
    - platform: state
      entity_id: binary_sensor.anybodyhome
      to: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: tts.picotts_say
      entity_id: media_player.hall_speaker
      data:
          message: System armed
    - service: notify.xmpp_proycon
      data:
          message: "System armed"
    - service: notify.xmpp_hans
      data:
          message: "System armed"
- id: disarm_when_home
  alias: 'Disarm when home'
  trigger:
    - platform: state
      entity_id: binary_sensor.anybodyhome
      to: 'on'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.xmpp_proycon
      data:
          message: "System disarmed"
    - service: notify.xmpp_hans
      data:
          message: "System disarmed"
- id: front_door_closed
  alias: "Front Door closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'on'
      to: 'off'
  action:
    - service: script.turn_off
      entity_id: script.front_door_still_open
- id: front_door_opened
  alias: "Front door opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.front_door_still_open
    - service: script.turn_off
      entity_id: script.reset_ipcam
    - service: input_select.select_option
      data:
          entity_id: input_select.ipcam_direction
          option: Front
    - delay:
        seconds: 10
    - service: script.turn_on
      entity_id: script.reset_ipcam
- id: back_door_closed
  alias: "back Door closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      from: 'on'
      to: 'off'
  action:
    - service: script.turn_off
      entity_id: script.back_door_still_open
- id: back_door_opened
  alias: "back door opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.back_door_still_open
    - service: script.turn_off
      entity_id: script.reset_ipcam
    - service: input_select.select_option
      data:
          entity_id: input_select.ipcam_direction
          option: Back
    - delay:
        seconds: 10
    - service: script.turn_on
      entity_id: script.reset_ipcam





#TODO: turn lights on and off in the morning
#TODO: alarm
#TODO: presence greeting
#TODO: door still open notifications
#TODO: wake up clock
