#------------ Startup notification ------------------------
- alias: Startup
  hide_entity: True
  trigger:
      platform: homeassistant
      event: start
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Home automation started
      - service: shell_command.snapshot_clear_locks #clear all snapshot locks on startup
#------------ Snapshots ------------------------
- id: snapshots_frontdoor
  alias: Frontdoor snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/9' #every ten seconds
  action:
    - service: shell_command.snapshot_frontdoor
- id: snapshots_hallupstairs
  alias: Hall upstairs snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/11' #every eleven seconds
  action:
    - service: shell_command.snapshot_hallupstairs
- id: snapshots_livingroom
  alias: Living room camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every five seconds
  action:
    - service: shell_command.snapshot_livingroom
- id: snapshots_street
  alias: Street camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every three seconds
  action:
    - service: shell_command.snapshot_street
- id: snapshots_garden
  alias: Garden camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/5' #every five seconds
  action:
    - service: shell_command.snapshot_garden
- alias: Archive snapshots
  hide_entity: False
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: shell_command.archive_snapshots


#TODO: turn lights on after sunset
#TODO: turn lights off at bedtime and after sunrise
#TODO: doorbell
#TODO: door notifications
#TODO: alarm
#TODO: presence greeting
#TODO: wake up clock
