#------------ Startup notification ------------------------
- alias: Startup
  hide_entity: True
  trigger:
      platform: homeassistant
      event: start
  action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Home automation started
      - service: shell_command.snapshot_clear_locks #clear all snapshot locks on startup
      - service: script.turn_on  #trigger RPi slaves to send their known statusses again
        data:
            entity_id: "script.trigger_slave_poll"
#------------ Snapshots ------------------------
- id: snapshots_frontdoor
  alias: Frontdoor snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/9' #every ten seconds
  action:
    - service: shell_command.snapshot_frontdoor
- id: snapshots_hallupstairs
  alias: Hall upstairs snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/11' #every eleven seconds
  action:
    - service: shell_command.snapshot_hallupstairs
- id: snapshots_livingroom
  alias: Living room camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every five seconds
  action:
    - service: shell_command.snapshot_livingroom
- id: snapshots_street
  alias: Street camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/3' #every three seconds
  action:
    - service: shell_command.snapshot_street
- id: snapshots_garden
  alias: Garden camera snapshots
  hide_entity: False
  trigger:
    platform: time
    seconds: '/5' #every five seconds
  action:
    - service: shell_command.snapshot_garden
- alias: Archive snapshots
  hide_entity: False
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: shell_command.archive_snapshots
- alias: Door notification
  trigger:
      - platform: state
        entity_id: binary_sensor.frontdoor
        state: "on"
      - platform: state
        entity_id: binary_sensor.backdoor
        state: "on"
   condition:
      - condition: time
        after: '23:00:00'
        before: '05:00:00'
      - condition: state
        entity_id: binary_sensor.anybodyhome
        state: "on"
   action:
      - service: tts.picotts_say
        entity_id: media_player.hall_speaker
        data:
            message: Door open
- alias: Lights on in the evening







#TODO: turn lights on after sunset
#TODO: turn lights off at bedtime and after sunrise
#TODO: doorbell
#TODO: door notifications
#TODO: alarm
#TODO: presence greeting
#TODO: wake up clock
