homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5

weblink:
    entities:
        - name: Kodi Control Interface
          url: !secret kodi_pi1_url
          icon: mdi:kodi
        - name: MPD Control Interface
          url: !secret mpd_url
          icon: mdi:music-box-outline
        - name: MPD Music Stream
          url: !secret music_stream_url
          icon: mdi:play-circle
        - name: AnaproyBoven Router
          url: !secret wifi_router_url
          icon: mdi:router-wireless
        - name: IPCam
          url: !secret ipcam_url
          icon: mdi:camcorder
        - name: KPN Router
          url: !secret kpn_router_url
          icon: mdi:upload-network

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
    exclude:
      domains:
        - shell_command
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs
        - script.update_kodi_library
        - script.avr_volup
        - script.avr_mute
        - script.avr_voldown
        - script.tvdecoder_playpause
        - script.tvdecoder_left
        - script.tvdecoder_right
        - script.tvdecoder_up
        - script.tvdecoder_down
        - script.tvdecoder_ok
        - script.tvdecoder_back
        - script.tvdecoder_channelup
        - script.tvdecoder_channeldown
        - script.tvdecoder_0
        - script.tvdecoder_1
        - script.tvdecoder_2
        - script.tvdecoder_3
        - script.tvdecoder_4
        - script.tvdecoder_5
        - script.tvdecoder_6
        - script.tvdecoder_7
        - script.tvdecoder_8
        - script.tvdecoder_9
        - script.tvdecoder_npo1
        - script.tvdecoder_npo2
        - script.tvdecoder_npo3
        - script.tvdecoder_rtl4
        - script.tvdecoder_veronica
        - script.tvdecoder_een
        - script.tvdecoder_canvas
        - script.tvdecoder_bbc1st
        - script.tvdecoder_bbc1
        - script.tvdecoder_bbc2
        - script.tvdecoder_ard
        - script.tvdecoder_zdf
        - script.tvdecoder_wdr
        - script.tvdecoder_arte
        - script.tvdecoder_tv5monde
        - script.tvdecoder_rai1

# View all events in a logbook
logbook:
    exclude:
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs

# Track the sun
sun:

zwave:
    usb_path: /dev/ttyACM0
    debug: true



shell_command:
    snapshot_livingroom: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh livingroom
    snapshot_street: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh street
    snapshot_garden: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh garden
    snapshot_frontdoor: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh frontdoor
    snapshot_hallupstairs: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh hallupstairs
    archive_snapshots: /home/homeautomation/homeassistant/scripts/camera/archive.sh
    event_snapshots: /home/homeautomation/homeassistant/scripts/camera/eventsnapshots.sh "{{ cam }}" "{{ delay }}"
    snapshot_clear_locks: find . -type f -name "/home/homeautomation/homeassistant/snapshots/*.lock" | xargs rm
    streetcam_reset_1: !secret streetcam_noir_command
    streetcam_reset_2: !secret streetcam_quality_command

rest_command:
    ipcam_topreset:
        url: 'http://{{ ip }}/cgi/ptdc.cgi?command=goto_preset_position&index={{ index }}'
        username: !secret ipcam_user
        password: !secret ipcam_password

alarm_control_panel:
    - platform: manual
      name: Alarm System
      trigger_time: 5

device_tracker:
    - platform: tplink
      host: !secret wifirouter_host
      username: !secret wifirouter_user
      password: !secret wifirouter_pass
    - platform: ping
      hosts:
          pi1: !secret pi1_ip
          pi2: !secret pi2_ip
          pi3: !secret pi3_ip

# Text to speech
tts:
  platform: picotts
  language: 'en-GB'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include cameras.yaml


input_select:
    ipcam_direction:
        name: Camera Direction Living room
        options:
            - Hall
            - Dresser
            - Back
            - TV
            - Couch
            - Front
    fireplace:
        name: Fireplace
        options:
            - Fire
            - Lamp
            - Ambilight
            - Rainbow Cycle
            - Colorcycle Fast
            - Colorcycle
            - Colorcycle Slow
            - Sirene
            - Red Cycle
            - Green Cycle
            - Blue Cycle
            - Red
            - Green
            - Blue
            - Yellow
            - Purple
            - Cyan
            - White
    dresser_ambilight:
        name: Dresser Ambilight
        options:
            - Fire
            - Lamp
            - Ambilight
            - Rainbow Cycle
            - Colorcycle Fast
            - Colorcycle
            - Colorcycle Slow
            - Sirene
            - Red Cycle
            - Green Cycle
            - Blue Cycle
            - Red
            - Green
            - Blue
            - Yellow
            - Purple
            - Cyan
            - White

input_slider:
    fireplace_brightness:
        name: Fireplace brightness
        min: 0
        max: 255
        step: 1
        initial: 255
    dresser_ambilight_brightness:
        name: Dresser Ambilight brightness
        min: 0
        max: 255
        step: 1
        initial: 255
    wake_up_hour:
        name: Wake up Hour
        icon: mdi:timer
        initial: 9
        min: 0
        max: 23
        step: 1
    wake_up_minutes:
        name: Wake up Minutes
        icon: mdi:timer
        initial: 0
        min: 0
        max: 59
        step: 5

input_boolean:
    inside_house:
        name: inside house? #anybody
        initial: on
    proycon_inside_house:
        name: Proycon inside house?
        initial: on
    hans_inside_house:
        name: Hans inside house?
        initial: on

sensor:
    - platform: buienradar #weather prediction
      name: Weather
      monitored_conditions:
          - symbol
          - temperature
    - platform: time_date
      display_options:
          - 'time'
    - platform: template
      sensors:
          wake_up_time:
            friendly_name: 'Wake up Time'
            value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.wake_up_hour") | int, states("input_slider.wake_up_minutes") | int) }}'
    - platform: mqtt
      name: Temperature Living Room
      unit_of_measurement: °C
      state_topic: "home/sensor/temperature_living_room"
    - platform: mqtt
      name: Humidity Living Room
      unit_of_measurement: "%"
      state_topic: "home/sensor/humidity_living_room"




binary_sensor doorbell:
    platform: mqtt
    name: Doorbell
    state_topic: "home/binary_sensor/doorbell"

binary_sensor frontdoor:
    platform: mqtt
    name: Front Door
    state_topic: "home/binary_sensor/frontdoor"
    device_class: opening

binary_sensor backdoor:
    platform: mqtt
    name: Back Door
    state_topic: "home/binary_sensor/backdoor"
    device_class: opening

binary_sensor bedroomwindow_right:
    platform: mqtt
    name: Bedroom window Right
    state_topic: "home/binary_sensor/bedroomwindow_right"
    device_class: opening

binary_sensor bedroomwindow_left:
    platform: mqtt
    name: Bedroom window Left
    state_topic: "home/binary_sensor/bedroomwindow_left"
    device_class: opening


binary_sensor pir_living_room:
    platform: mqtt
    name: PIR Living Room
    state_topic: "home/binary_sensor/pir_living_room"
    device_class: motion


binary_sensor:
    platform: template
    sensors:
      anybodyhome:
        friendly_name: "Anybody home?"
        value_template: '{% if is_state("device_tracker.proyphone","home") or is_state("device_tracker.hansphone","home") %}True{% else %}False{% endif %}'
        entity_id:
            - device_tracker.proyphone
            - device_tracker.hansphone
      pir_kitchen:
        friendly_name: "PIR Kitchen"
        value_template: '{{ is_state("sensor.fibaro_multisensor_burglar", "8") }}'
        entity_id:
            - sensor.fibaro_multisensor_burglar
        device_class: motion


switch tv_spots:
    platform: mqtt
    name: TV Spots
    state_topic: "home/433send/get/elro/31/E"
    command_topic: "home/433send/set/pi1/elro/31/E"
switch office:
    platform: mqtt
    name: Office
    state_topic: "home/433send/get/elro/15/A"
    command_topic: "home/433send/set/pi2/elro/15/A"
switch front_room:
    platform: mqtt
    name: Front Room
    state_topic: "home/433send/get/oldkaku/M/10"
    command_topic: "home/433send/set/pi1/oldkaku/M/10"
switch midspots:
    platform: mqtt
    name: Midspots
    state_topic: "home/433send/get/elro/31/B"
    command_topic: "home/433send/set/pi2/elro/31/B"
switch back_room:
    platform: mqtt
    name: Back room
    state_topic: "home/433send/get/elro/31/A"
    command_topic: "home/433send/set/pi2/elro/31/A"
switch back_corner:
    platform: mqtt
    name: Back Corner
    state_topic: "home/433send/get/elro/31/C"
    command_topic: "home/433send/set/pi2/elro/31/C"
switch kitchen:
    platform: mqtt
    name: Kitchen
    state_topic: "home/433send/get/newkaku/120/7"
    command_topic: "home/433send/set/pi1/newkaku/120/7"
switch bedroom:
    platform: mqtt
    name: Bedroom
    state_topic: "home/433send/get/elro/15/C"
    command_topic: "home/433send/set/pi2/elro/15/C"
switch garden:
    platform: mqtt
    name: Garden
    state_topic: "home/433send/get/elro/23/A"
    command_topic: "home/433send/set/pi2/elro/23/A"
switch balcony:
    platform: mqtt
    name: Balcony
    state_topic: "home/433send/get/newkaku/121/9"
    command_topic: "home/433send/set/pi2/newkaku/121/9"
    #state_topic: "home/elro/get/23/2"
    #command_topic: "home/elro/set/pi2/23/2"
switch hall:
    platform: mqtt
    name: Hall
    state_topic: "home/433send/get/elro/15/B"
    command_topic: "home/433send/set/pi1/elro/15/B"
switch roof:
    platform: mqtt
    name: Roof
    state_topic: "home/433send/get/newkaku/121/8"
    command_topic: "home/433send/set/pi2/newkaku/121/8"
    #state_topic: "home/elro/get/23/4"
    #command_topic: "home/elro/set/pi2/23/4"
switch porch:
    platform: mqtt
    name: Porch
    state_topic: "home/433send/get/oldkaku/M/11"
    command_topic: "home/433send/set/pi1/oldkaku/M/11"
switch bathroom_vent:
    platform: mqtt
    name: Bathroom Vent
    state_topic: "home/433send/get/newkaku/121/7"
    command_topic: "home/433send/set/pi2/newkaku/121/7"
    #state_topic: "home/elro/get/23/4"
    #command_topic: "home/elro/set/pi2/23/4"
switch tv_decoder:
    platform: mqtt
    name: TV Decoder
    command_topic: "home/ir_send/pi1"
    payload_on: '{"device":"VIP1853","key":"POWER"}'
    payload_off: '{"device":"VIP1853","key":"POWER"}'
switch pi1_kodi:
    platform: mqtt
    name: Pi1 Kodi
    command_topic: "home/kodi/set/pi1"
    state_topic: "home/kodi/set/pi1"
switch pi1_xorg:
    platform: mqtt
    name: Pi1 Xorg
    command_topic: "home/xorg/set/pi1"
    state_topic: "home/xorg/get/pi1"
switch pi2_kodi:
    platform: mqtt
    name: Pi2 Kodi
    command_topic: "home/kodi/set/pi2"
    state_topic: "home/kodi/get/pi2"
switch pi2_xorg:
    platform: mqtt
    name: Pi2 Xorg
    command_topic: "home/xorg/set/pi2"
    state_topic: "home/xorg/get/pi2"


hdmi_cec:
    host: !secret pi1_ip
    types:
       hdmi_cec.hdmi_0: switch #will expose a switch.hdmi_0 entity

media_player hall_speaker:
    - platform: vlc
      name: Hall speaker
      arguments: '--alsa-audio-device=hw:0,0'

media_player yamaha_receiver:
  - platform: yamaha
    host: !secret avr_ip
    source_names:
        HDMI1: "TV Decoder"
        HDMI2: "Pi1"

media_player mpd:
  - platform: mpd
    host: 127.0.0.1
    password: !secret mpd_password

media_player kodi:
    - platform: kodi
      name: Kodi
      host: !secret pi1_ip
      username: !secret kodi_username
      password: !secret kodi_password
      #turn_on_action:
      #    - service: script.turn_on
      #      data:
      #          entity_id: script.media_centre
      #turn_off_action:
      #    - service: script.turn_off
      #      data:
      #          entity_id: script.turn_media_off


notify:
  - name: xmpp_proycon
    platform: xmpp
    sender: !secret xmpp_sender
    password: !secret xmpp_password
    recipient: !secret xmpp_proycon
  - name: xmpp_hans
    platform: xmpp
    sender: !secret xmpp_sender
    password: !secret xmpp_password
    recipient: !secret xmpp_hans
  - name: mail_both
    platform: smtp
    sender: !secret xmpp_sender
    server: 127.0.0.1
    recipient:
        - !secret xmpp_proycon
        - !secret xmpp_hans
  - name: sms
    platform: message_bird
    api_key: !secret messagebird_apikey

#MQTT
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: master
    keepalive: 60
    username: homeassistant
    password: !secret api_password


#mqtt_eventstream:
#  publish_topic: master
#  subscribe_topic: slaves/#
