homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
    exclude:
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs

# View all events in a logbook
logbook:
    exclude:
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs

# Track the sun
sun:

# Weather Prediction
sensor:
    - platform: buienradar
      name: Weather
      monitored_conditions:
          - symbol
          - temperature

binary_sensor:
    - platform: template
      sensors: # Persistence for sensors from slaves (redefinitions)
          doorbell:
            friendly_name: Doorbell
            value_template: "{% if states.binary_sensor.slave_doorbell %}{{ states('binary_sensor.slave_doorbell') }}{% else %}{{ states('binary_sensor.doorbell') }}{% endif %}"
            entity_id: binary_sensor.slave_doorbell
            device_class: opening
          frontdoor:
            friendly_name: Front Door
            value_template: "{% if states.binary_sensor.slave_frontdoor %}{{ states('binary_sensor.slave_frontdoor') }}{% else %}{{ states('binary_sensor.frontdoor') }}{% endif %}"
            entity_id: binary_sensor.slave_frontdoor
            device_class: opening
          backdoor:
            friendly_name: Back Door
            value_template: "{% if states.binary_sensor.slave_backdoor %}{{ states('binary_sensor.slave_backdoor') }}{% else %}{{ states('binary_sensor.backdoor') }}{% endif %}"
            entity_id: binary_sensor.slave_backdoor
            device_class: opening
          bedroomwindow_right:
            friendly_name: Bedroom window Right
            value_template: "{% if states.binary_sensor.slave_bedroomwindow_right %}{{ states('binary_sensor.slave_bedroomwindow_right') }}{% else %}{{ states('binary_sensor.bedroomwindow_right') }}{% endif %}"
            entity_id: binary_sensor.slave_bedroomwindow_right
            device_class: opening
          bedroomwindow_left:
            friendly_name: Bedroom window Left
            value_template: "{% if states.binary_sensor.slave_bedroomwindow_left %}{{ states('binary_sensor.slave_bedroomwindow_left') }}{% else %}{{ states('binary_sensor.bedroomwindow_left') }}{% endif %}"
            entity_id: binary_sensor.slave_bedroomwindow_left
            device_class: opening
switch:
    - platform: template
      switches: # Persistence for switches from slaves (redefinitions)
        tv_spots:
            friendly_name: TV Spots
            value_template: "{% if states.switch.slave_tv_spots %}{{ is_state('switch.slave_tv_spots','on') }}{% else %}{{ is_state('switch.tv_spots','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_tv_spots
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_tv_spots
        front_room:
            friendly_name: Front Room
            value_template: "{% if states.switch.slave_front_room %}{{ is_state('switch.slave_front_room','on') }}{% else %}{{ is_state('switch.front_room','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_front_room
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_front_room
        hall:
            friendly_name: Hall
            value_template: "{% if states.switch.slave_hall %}{{ is_state('switch.slave_hall','on') }}{% else %}{{ is_state('switch.hall','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_hall
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_hall
        midspots:
            friendly_name: Midspots
            value_template: "{% if states.switch.slave_midspots %}{{ is_state('switch.slave_midspots','on') }}{% else %}{{ is_state('switch.midspots','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_midspots
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_midspots
        back_room:
            friendly_name: Back room
            value_template: "{% if states.switch.slave_back_room %}{{ is_state('switch.slave_back_room','on') }}{% else %}{{ is_state('switch.back_room','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_back_room
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_back_room
        back_corner:
            friendly_name: Back corner
            value_template: "{% if states.switch.slave_back_corner %}{{ is_state('switch.slave_back_corner','on') }}{% else %}{{ is_state('switch.back_corner','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_back_corner
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_back_corner
        office:
            friendly_name: Office
            value_template: "{% if states.switch.slave_office %}{{ is_state('switch.slave_office','on') }}{% else %}{{ is_state('switch.office','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_office
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_office
        bedroom:
            friendly_name: Bedroom
            value_template: "{% if states.switch.slave_bedroom %}{{ is_state('switch.slave_bedroom','on') }}{% else %}{{ is_state('switch.bedroom','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_bedroom
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_bedroom
        garden:
            friendly_name: Garden
            value_template: "{% if states.switch.slave_garden %}{{ is_state('switch.slave_garden','on') }}{% else %}{{ is_state('switch.garden','on') }}{% endif %}"
            turn_on:
                service: switch.turn_on
                entity_id: switch.slave_garden
            turn_off:
                service: switch.turn_off
                entity_id: switch.slave_garden

media_player hall_speaker:
    - platform: vlc
      name: hall_speaker
      arguments: '--alsa-audio-device=hw:0,0'

camera:
    - id: livingroom
      platform: local_file
      name: Living Room
      file_path: /home/homeautomation/homeassistant/snapshots/_livingroom.jpg
    - id: street
      platform: local_file
      name: Street
      file_path: /home/homeautomation/homeassistant/snapshots/_street.jpg
    - id: frontdoor
      platform: local_file
      name: Front door
      file_path: /home/homeautomation/homeassistant/snapshots/_frontdoor.jpg
    - id: hallupstairs
      platform: local_file
      name: Hall upstairs
      file_path: /home/homeautomation/homeassistant/snapshots/_hallupstairs.jpg
    - id: garden
      platform: local_file
      name: Garden
      file_path: /home/homeautomation/homeassistant/snapshots/_garden.jpg
    #- platform: generic
    #  name: Streetcam
    #  still_image_url: !secret streetcam_url
    #- platform: generic
    #  name: Gardencam
    #  still_image_url: !secret gardencam_url

shell_command:
    snapshot_livingroom: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh livingroom
    snapshot_street: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh street
    snapshot_garden: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh garden
    snapshot_frontdoor: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh frontdoor
    snapshot_hallupstairs: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh hallupstairs
    archive_snapshots: /home/homeautomation/homeassistant/scripts/camera/archive.sh
    snapshot_clear_locks: find . -type f -name "*.lock" | xargs rm



device_tracker:
    - platform: tplink
      host: !secret wifirouter_host
      username: !secret wifirouter_user
      password: !secret wifirouter_pass
    - platform: ping
      hosts:
          pi1: !secret pi1_ip
          pi2: !secret pi2_ip
          pi3: !secret pi3_ip

# Text to speech
tts:
  platform: picotts
  language: 'en-GB'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#MQTT
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: master
    keepalive: 60
    username: homeassistant
    password: !secret api_password


mqtt_eventstream:
  publish_topic: master
  subscribe_topic: slaves/#
