homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
    exclude:
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs

# View all events in a logbook
logbook:
    exclude:
      entities:
        - automation.snapshots_frontdoor
        - automation.snapshots_garden
        - automation.snapshots_street
        - automation.snapshots_livingroom
        - automation.snapshots_hallupstairs

# Track the sun
sun:




shell_command:
    snapshot_livingroom: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh livingroom
    snapshot_street: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh street
    snapshot_garden: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh garden
    snapshot_frontdoor: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh frontdoor
    snapshot_hallupstairs: /home/homeautomation/homeassistant/scripts/camera/takesnapshot.sh hallupstairs
    archive_snapshots: /home/homeautomation/homeassistant/scripts/camera/archive.sh
    snapshot_clear_locks: find . -type f -name "*.lock" | xargs rm

rest_command:
    ipcam_topreset:
        url: 'http://{{ ip }}/cgi/ptdc.cgi?command=goto_preset_position&index={{ index }}'
        username: !secret ipcam_user
        password: !secret ipcam_password

alarm_control_panel:
    - platform: manual
      name: Alarm System
      trigger_time: 5

device_tracker:
    - platform: tplink
      host: !secret wifirouter_host
      username: !secret wifirouter_user
      password: !secret wifirouter_pass
    - platform: ping
      hosts:
          pi1: !secret pi1_ip
          pi2: !secret pi2_ip
          pi3: !secret pi3_ip

# Text to speech
tts:
  platform: picotts
  language: 'en-GB'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include cameras.yaml


input_select:
    ipcam_direction:
        name: Camera Direction Living room
        options:
            - Hall
            - Dresser
            - Back
            - TV
            - Couch
            - Front
    fireplace:
        name: Fireplace
        options:
            - Fire
            - Lamp
            - Ambilight
            - Rainbow Cycle
            - Colorcycle Fast
            - Colorcycle
            - Colorcycle Slow
            - Sirene
            - Red Cycle
            - Green Cycle
            - Blue Cycle
            - Red
            - Green
            - Blue
            - Yellow
            - Purple
            - Cyan
            - White

input_slider:
    fireplace_brightness:
        name: Fireplace brightness
        min: 0
        max: 255
        step: 1
        initial: 255

sensor:
    - platform: buienradar #weather prediction
      name: Weather
      monitored_conditions:
          - symbol
          - temperature

binary_sensor doorbell:
    platform: mqtt
    name: Doorbell
    state_topic: "home/binary_sensor/doorbell"

binary_sensor frontdoor:
    platform: mqtt
    name: Front Door
    state_topic: "home/binary_sensor/frontdoor"
    device_class: opening

binary_sensor backdoor:
    platform: mqtt
    name: Back Door
    state_topic: "home/binary_sensor/backdoor"
    device_class: opening

binary_sensor bedroomwindow_right:
    platform: mqtt
    name: Bedroom window Right
    state_topic: "home/binary_sensor/bedroomwindow_right"
    device_class: opening

binary_sensor bedroomwindow_left:
    platform: mqtt
    name: Bedroom window Left
    state_topic: "home/binary_sensor/bedroomwindow_left"
    device_class: opening

binary_sensor:
    platform: template
    sensors:
      anybodyhome:
        friendly_name: "Anybody home?"
        value_template: '{% if is_state("device_tracker.proyphone","home") or is_state("device_tracker.hansphone","home") %}True{% else %}False{% endif %}'
        entity_id:
            - device_tracker.proyphone
            - device_tracker.hansphone
        device_class: occupancy

switch tv_spots:
    platform: mqtt
    name: TV Spots
    state_topic: "home/elro/get/beneden/16"
    command_topic: "home/elro/set/pi1/beneden/16"
switch office:
    platform: mqtt
    name: Office
    state_topic: "home/elro/get/boven/1"
    command_topic: "home/elro/set/pi2/boven/1"
switch front_room:
    platform: mqtt
    name: Front Room
    state_topic: "home/kaku/get/M/10"
    command_topic: "home/kaku/set/pi1/M/10"
switch midspots:
    platform: mqtt
    name: Midspots
    state_topic: "home/elro/get/beneden/2"
    command_topic: "home/elro/set/pi2/beneden/2"
switch back_room:
    platform: mqtt
    name: Back room
    state_topic: "home/elro/get/beneden/1"
    command_topic: "home/elro/set/pi2/beneden/1"
switch back_corner:
    platform: mqtt
    name: Back Corner
    state_topic: "home/elro/get/beneden/4"
    command_topic: "home/elro/set/pi2/beneden/4"
switch bedroom:
    platform: mqtt
    name: Bedroom
    state_topic: "home/elro/get/boven/4"
    command_topic: "home/elro/set/pi2/boven/4"
switch garden:
    platform: mqtt
    name: Garden
    state_topic: "home/elro/get/buiten/1"
    command_topic: "home/elro/set/pi2/buiten/1"
switch balcony:
    platform: mqtt
    name: Balcony
    state_topic: "home/elro/get/buiten/2"
    command_topic: "home/elro/set/pi2/buiten/2"
switch hall:
    platform: mqtt
    name: Hall
    state_topic: "home/elro/get/boven/2"
    command_topic: "home/elro/set/pi1/boven/2"
switch roof:
    platform: mqtt
    name: Roof
    state_topic: "home/elro/get/buiten/4"
    command_topic: "home/elro/set/pi2/buiten/4"
switch tv_decoder:
    platform: mqtt
    name: TV Decoder
    command_topic: "home/ir_send/pi1"
    payload_on: '{"device":"VIP1853","key":"POWER"}'
    payload_off: '{"device":"VIP1853","key":"POWER"}'

hdmi_cec:
    host: !secret pi1_ip
    types:
       hdmi_cec.hdmi_0: switch #will expose a switch.hdmi_0 entity

media_player hall_speaker:
    - platform: vlc
      name: hall_speaker
      arguments: '--alsa-audio-device=hw:0,0'

media_player yamaha_receiver:
  - platform: yamaha
    host: !secret avr_ip
    source_names:
        HDMI1: "TV Decoder"
        HDMI2: "Pi1"
#MQTT
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: master
    keepalive: 60
    username: homeassistant
    password: !secret api_password


#mqtt_eventstream:
#  publish_topic: master
#  subscribe_topic: slaves/#
