title: Home
# Include external resources
resources:
  - url: /local/custom-ui/button-card.js
    type: js
views:
  - id: home
    icon: mdi:home
    title: Home
    #theme: darkgreen
    cards:
        - type: picture-elements
          image: /local/floorplans/downstairs.png
          elements:
              - type: image
                entity: switch.tv_spots
                tap_action:
                    action: toggle
                hold_action:
                    action: more-info
                image: /local/icons/light_bulb_off.png
                state_image:
                  'on': /local/icons/light_bulb_on.png
                state_filter:
                  'on': brightness(130%) saturate(1.5) drop-shadow(0px 0px 10px gold)
                  'off': brightness(80%) saturate(0.8)
                style:
                  top: 38%
                  left: 50%
                  width: 7%
                  padding: 50px 50px 100px 50px
              - type: state-label
                entity: sensor.dogsensor_temperature
                style:
                  top: 43%
                  left: 50%
                  background: center
                  text-align: center
                  font-size: 12px
                  color: blue
                  font-family: Helvetica
          - type: state-icon
            entity: binary_sensor.pir_jaiko
            style:
              top: 95%
              left: 32%


